version: 3.8

services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${DB_EXPOSE_PORT}
    command: ["postgres", "-N", "${MAX_CONNECTIONS}"]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
